services:
  mysql:
    image: mysql:5.7
    container_name: exchangeRate
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio1
      MYSQL_PASSWORD: root
    ports:
      - 3307:3307